export enum STORAGE {
    RE_OWNERS_1 = 'RE_OWNERS-1',
    RE_OWNERS_2 = 'RE_OWNERS-2',
    RE_TENANT_1 = 'RE_TENANT-1',
    RE_TENANT_2 = 'RE_TENANT-2',
    RE_PROPERTY = 'RE_PROPERTY',
    RE_AGREEMENTY = 'RE_AGREEMENTY',
    RE_USER = 'RE_USER'
}

