export const form = [
  [
    {
      label: 'O proprietário(a) é:',
      placeholder: 'Escolha',
      name: 'person',
      model: '',
      select: true,
      option: ['Pessoa Física (CPF)', 'Pessoa jurídica (PJ)'],
    },
    {
      label: 'Nome completo:',
      placeholder: 'Ex: João da Silva',
      model: '',
      name: 'name',
      type: 'text',
      max: 80,
    },
    {
      label: 'Nacionalidade',
      placeholder: 'Escolha',
      name: 'nationality',
      model: '',
      select: true,
      option: ['Brasileiro(a)', 'Estrangeiro(a)'],
    },
    {
      label: 'Estado Civil:',
      placeholder: 'Escolha',
      name: 'marital',
      model: '',
      select: true,
      option: ['Solteiro(a)', 'Casado(a)'],
    },
    {
      label: 'Profissão:',
      placeholder: 'Ex: Gerente, Mecânico, Atendente...',
      model: '',
      name: 'profession',
      type: 'text',
      max: 50,
    },
    {
      label: 'CPF',
      placeholder: 'Ex: 000.000.000-00',
      type: 'text',
      name: 'cpf',
      model: '',
      max: 14,
    },
    {
      label: 'E-mail (opcional)',
      placeholder: 'Ex: jose@gmail.com',
      model: '',
      name: 'email',
      type: 'email',
      max: 60,
    },
  ],
  [
    {
      label: 'CEP',
      placeholder: 'Ex: 00000-000',
      type: 'text',
      name: 'cep',
      model: '',
      max: 9,
    },
    {
      label: 'Rua:',
      placeholder: 'Rua: Amado Rui',
      name: 'street',
      type: 'text',
      model: '',
      max: 80,
    },
    {
      label: 'Número:',
      placeholder: 'Ex: 123',
      model: '',
      name: 'number',
      type: 'text',
      max: 10,
    },
    {
      label: 'Complemento:',
      placeholder: 'Ex: Bloco A, Apto 258',
      model: '',
      name: 'complement',
      type: 'text',
      max: 50,
    },
    {
      label: 'Bairro:',
      placeholder: 'Ex: Jardim',
      model: '',
      name: 'neighborhood',
      type: 'text',
      max: 50,
    },
    {
      label: 'Cidade:',
      placeholder: 'Ex: São Paulo',
      model: '',
      name: 'city',
      type: 'text',
      max: 40,
    },
    {
      label: 'UF:',
      placeholder: 'Ex: SP',
      model: '',
      name: 'uf',
      type: 'text',
      max: 2,
    },
  ],
  [
    {
      label: 'O inquilino(a) é:',
      placeholder: 'Escolha',
      name: 'person',
      model: '',
      select: true,
      option: ['Pessoa Física (CPF)', 'Pessoa jurídica (PJ)'],
    },
    {
      label: 'Nome completo:',
      placeholder: 'Ex: João da Silva',
      model: '',
      name: 'name',
      type: 'text',
      max: 80,
    },
    {
      label: 'Nacionalidade',
      placeholder: 'Escolha',
      name: 'nationality',
      model: '',
      select: true,
      option: ['Brasileiro(a)', 'Estrangeiro(a)'],
    },
    {
      label: 'Estado Civil:',
      placeholder: 'Escolha',
      name: 'marital',
      model: '',
      select: true,
      option: ['Solteiro(a)', 'Casado(a)'],
    },
    {
      label: 'Profissão:',
      placeholder: 'Ex: Gerente, Mecânico, Atendente...',
      model: '',
      name: 'profession',
      type: 'text',
      max: 50,
    },
    {
      label: 'CPF',
      placeholder: 'Ex: 000.000.000-00',
      type: 'text',
      name: 'cpf',
      model: '',
      max: 14,
    },
    {
      label: 'E-mail (opcional)',
      placeholder: 'Ex: jose@gmail.com',
      model: '',
      name: 'email',
      type: 'email',
      max: 60,
    },
  ],
  [
    {
      label: 'CEP',
      placeholder: 'Ex: 00000-000',
      type: 'text',
      name: 'cep',
      model: '',
      max: 9,
    },
    {
      label: 'Rua:',
      placeholder: 'Rua: Amado Rui',
      name: 'street',
      type: 'text',
      model: '',
      max: 80,
    },
    {
      label: 'Número:',
      placeholder: 'Ex: 123',
      model: '',
      name: 'number',
      type: 'text',
      max: 10,
    },
    {
      label: 'Complemento:',
      placeholder: 'Ex: Bloco A, Apto 258',
      model: '',
      name: 'complement',
      type: 'text',
      max: 50,
    },
    {
      label: 'Bairro:',
      placeholder: 'Ex: Jardim',
      model: '',
      name: 'neighborhood',
      type: 'text',
      max: 50,
    },
    {
      label: 'Cidade:',
      placeholder: 'Ex: São Paulo',
      model: '',
      name: 'city',
      type: 'text',
      max: 40,
    },
    {
      label: 'UF:',
      placeholder: 'Ex: SP',
      model: '',
      name: 'uf',
      type: 'text',
      max: 2,
    },
  ],
  [
    {
      label: 'CEP do imóvel',
      placeholder: 'Ex: 00000-000',
      type: 'text',
      name: 'cep',
      model: '',
      max: 9,
    },
    {
      label: 'Rua:',
      placeholder: 'Rua: Amado Rui',
      name: 'street',
      type: 'text',
      model: '',
      max: 80,
    },
    {
      label: 'Número:',
      placeholder: 'Ex: 123',
      model: '',
      name: 'number',
      type: 'text',
      max: 10,
    },
    {
      label: 'Complemento:',
      placeholder: 'Ex: Bloco A, Apto 258',
      model: '',
      name: 'complement',
      type: 'text',
      max: 50,
    },
    {
      label: 'Bairro:',
      placeholder: 'Ex: Jardim',
      model: '',
      name: 'neighborhood',
      type: 'text',
      max: 50,
    },
    {
      label: 'Cidade:',
      placeholder: 'Ex: São Paulo',
      model: '',
      name: 'city',
      type: 'text',
      max: 40,
    },
    {
      label: 'UF:',
      placeholder: 'Ex: SP',
      model: '',
      name: 'uf',
      type: 'text',
      max: 2,
    },
  ],
  [
    {
      label: 'Duração',
      placeholder: 'Ex: 12 meses',
      type: 'text',
      name: 'duration',
      model: '',
      max: 20,
    },
    {
      label: 'Data de início:',
      name: 'date-init',
      type: 'date',
      model: '',
      max: 10,
    },
    {
      label: 'Valor do aluguel:',
      placeholder: 'Ex: 1.500,00',
      model: '',
      name: 'rental-value',
      type: 'text',
      max: 15,
    },
    {
      label: 'Prazo para pagamentos (dias):',
      placeholder: 'Ex: 5',
      model: '',
      name: 'term',
      type: 'text',
      max: 3,
    },
    {
      label: 'Valor do caução:',
      placeholder: 'Ex: 5.000,00',
      model: '',
      name: 'deposit',
      type: 'text',
      max: 15,
    },
    {
      label: 'Multa por infração:',
      placeholder: 'Ex: 5.000,00',
      model: '',
      name: 'infringement',
      type: 'text',
      max: 15,
    },
    {
      label: 'Valor da rescisão:',
      placeholder: 'Ex: 2.000,00',
      model: '',
      name: 'termination',
      type: 'text',
      max: 15,
    },
  ],
];
